/**
 * Job Manager Service
 * Job Manager API for interacting with asynchronous batch jobs and workflows.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * An aggregation entry for a given label value.
 */
export interface AggregationEntry {
    /**
     * The label value for this aggregation entry.
     */
    label?: string;

    statusCounts?: models.StatusCounts;

}
