/**
 * Job Manager Service
 * Job Manager API for interacting with asynchronous batch jobs and workflows.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Jobs aggregated by label and status within the specified time frame.
 */
export interface AggregationResponse {
    summary?: models.StatusCounts;

    aggregations?: Array<models.Aggregation>;

}
