/**
 * Job Manager Service
 * Job Manager API for interacting with asynchronous batch jobs and workflows.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export enum TimeFrame {
    HOURS1 = <any> 'HOURS_1',
    HOURS8 = <any> 'HOURS_8',
    HOURS24 = <any> 'HOURS_24',
    DAYS7 = <any> 'DAYS_7',
    DAYS30 = <any> 'DAYS_30',
    ALLTIME = <any> 'ALL_TIME'
}
