version: 2
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^([A|a]pproved|:+1:|:thumbsup:|LGTM)'
    reject_regex: '^([R|r]ejected|:-1:|:thumbsdown:)'
  reject_value: -100 # any rejection means a failure
  reset_on_push:
    enabled: false
  reset_on_reopened:
    enabled: true
groups:
  master-review:
    required: 1
    author_approval:
      ignored: true
    teams:
      - verilywrite
      - broadwrite
    conditions:
      branches:
        - master
  pullapprove-admins:
    required: 1
    author_approval:
      ignored: true 
    conditions:
      files:
        - ".pullapprove.yml"
    teams:
      - bv-devops
