version: '2.1'
services:
  rebuild-swagger:
    image: eclipse-temurin:latest
    volumes:
      - ./:/base
    entrypoint: ["/bin/bash", "-c", "cd base && /base/scripts/rebuild_swagger.sh"]
  jmui:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    volumes:
      # Only mount a whitelist of top-level /ui files/directories; specifically
      # node_modules must not be included here. Mount only files required to run
      # the dev server. Anything required to install dependencies (npm install)
      # should instead be added via the Dockerfile. Updating dependencies
      # requires use of the slower docker compose build.
      - ./scripts:/scripts
      - ./ui/src:/ui/src
      - ./ui/tsconfig.json:/ui/tsconfig.json
      - ./ui/angular.json:/ui/angular.json
      - ./api:/ui/api
  cromwell:
    command: ["-b", ":8190", "-t", "60"]
    environment:
      - PATH_PREFIX=/api/v1
      - CROMWELL_CREDENTIALS=/app/jobs/config.json
      - CAPABILITIES_CONFIG=/app/jobs/capabilities_config.json
      - CROMWELL_URL=${CROMWELL_URL}
      - GUNICORN_CMD_ARGS=${GUNICORN_CMD_ARGS:-"--workers=5"}
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./api:/app/api
      - ./scripts:/scripts
      - ./servers/cromwell/jobs:/app/jobs
    ports:
      - 8190:8190
  jobs-proxy:
    # Child services must have links named "jmui", "jmapi".
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 4200:4200
