version: '2.1'
services:
  rebuild-swagger:
    extends:
      file: common-compose.yml
      service: rebuild-swagger
  jmui:
    extends:
      file: common-compose.yml
      service: jmui
    command: ["npm", "run-script", "ng", "--", "serve", "--host", "jmui"]
    volumes:
      - ${PWD}/ui/assets/environments/environment.cromwell.instance.json:/ui/src/assets/environments/environment.json
  cromwell:
    build:
      context: .
      dockerfile: servers/cromwell/Dockerfile.dev
    extends:
      file: common-compose.yml
      service: cromwell
    environment:
      - USE_CAAS=False
  jobs-proxy:
    extends:
      file: common-compose.yml
      service: jobs-proxy
    links:
      - jmui
      - cromwell:jmapi
