version: '2.1'
services:
  ui:
    extends:
      file: common-compose.yml
      service: ui
    command: ["npm", "run-script", "ng", "--", "serve", "--host", "ui", "--env=cromwell_caas"]
  cromwell:
    build:
      context: .
      dockerfile: servers/cromwell/Dockerfile
    extends:
      file: common-compose.yml
      service: cromwell
    environment:
      - CROMWELL_URL=${CROMWELL_URL:-https://cromwell.caas-dev.broadinstitute.org/api/workflows/v1}
      - USE_CAAS=True
  jobs-proxy:
    extends:
      file: common-compose.yml
      service: jobs-proxy
    links:
      - ui
      - cromwell:api
