version: '2.1'
services:
  jmui:
    extends:
      file: common-compose.yml
      service: jmui
    command: ["npm", "run-script", "ng", "--", "serve", "--host", "jmui", "--env=cromwell_dev"]
  cromwell:
    build:
      context: .
      dockerfile: servers/cromwell/Dockerfile
    extends:
      file: common-compose.yml
      service: cromwell
    environment:
      - USE_CAAS=False
  jobs-proxy:
    extends:
      file: common-compose.yml
      service: jobs-proxy
    links:
      - jmui
      - cromwell:jmapi
