version: '2'
services:
  jobs:
    build:
      context: .
      dockerfile: Dockerfile.dsub
    # Flags to gunicorn:
    # http://docs.gunicorn.org/en/stable/run.html#commonly-used-arguments
    command: ["-b", ":8190"]
    environment:
      # Avoid writing .pyc files back to the volume. Files generated this way
      # have restricted permissions set which cause errors on subsequent docker
      # builds.
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      # Mount the python source so that code changes don't require rebuilding
      # the image. Changes to requirements.txt will still require rebuilds.
      - ./servers/dsub/jobs:/app/jobs
    ports:
      - 8190:8190
