version: '2'
services:
  ui:
    extends:
      file: common-compose.yml
      service: ui
  dsub:
    extends:
      file: common-compose.yml
      service: dsub
    # privileged is needed in order to run ddel to kill local processes.
    privileged: true
    # This shares the host PID address space with the container so that host
    # processes can be checked on and killed
    pid: host
    environment:
      - PROVIDER_TYPE=local
    volumes:
      - /tmp/dsub-local:/tmp/dsub-local
      - /var/run/docker.sock:/var/run/docker.sock
  jobs-proxy:
    extends:
      file: common-compose.yml
      service: jobs-proxy
    links:
      - ui
      - dsub:api
