version: '2'
services:
  ui:
    extends:
      file: common-compose.yml
      service: ui
    # Use --host "ui" to match the container name, as this is how nginx will
    # access the UI on the network. This must match to avoid "Invalid Host"
    # errors. See also https://github.com/angular/angular-cli/issues/6349.
    command: ["npm", "run-script", "ng", "--", "serve", "--host", "ui", "--env=dsub_google"]
  dsub:
    build:
      context: servers/dsub
      dockerfile: Dockerfile
    extends:
      file: common-compose.yml
      service: dsub
    environment:
      - PROVIDER_TYPE=google
      - REQUIRES_AUTH=1
  jobs-proxy:
    extends:
      file: common-compose.yml
      service: jobs-proxy
    links:
      - ui
      - dsub:api
