version: '2.1'
services:
  rebuild-swagger:
    extends:
      file: common-compose.yml
      service: rebuild-swagger
  jmui:
    extends:
      file: common-compose.yml
      service: jmui
    # Use --host "jmui" to match the container name, as this is how nginx will
    # access the UI on the network. This must match to avoid "Invalid Host"
    # errors. See also https://github.com/angular/angular-cli/issues/6349.
    command: ["npm", "run-script", "ng", "--", "serve", "--host", "jmui"]
    volumes:
      - ${PWD}/ui/assets/environments/environment.dsub.local.json:/ui/src/assets/environments/environment.json
  dsub:
    build:
      context: servers
      dockerfile: dsub/Dockerfile.local
    extends:
      file: common-compose.yml
      service: dsub
    # privileged is needed in order to interact with the mounted docker socket.
    privileged: true
    # This shares the host PID address space with the container so that host
    # processes can be checked on and killed
    pid: host
    environment:
      - PROVIDER_TYPE=local
      - REQUIRES_AUTH=0
    volumes:
      - /tmp/dsub-local:/tmp/dsub-local
      - /var/run/docker.sock:/var/run/docker.sock
  jobs-proxy:
    extends:
      file: common-compose.yml
      service: jobs-proxy
    links:
      - jmui
      - dsub:jmapi
  aggregation-cache:
    extends:
      file: common-compose.yml
      service: aggregation-cache
