# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  # TODO(calbach): Add linting tests.
  build:
    # TODO(calbach): Get an image with nodejs/npm for UI test/lint.
    docker:
      - image: circleci/python:2.7

    working_directory: ~/job-monitor

    steps:
      - checkout
      - restore_cache:
          key: tox
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install tox
      - save_cache:
          key: tox
          paths:
            - "venv"

      # TODO(calbach): Cache the tox venvs per https://discuss.circleci.com/t/cached-venv-in-tox/1499.
      - run:
          # TODO(calbach): Re-enable these tests. Local fails due to
          # docker-in-docker issues. Google fails due to lack of auth.
          command: |
            source venv/bin/activate
            tox -c ./servers/dsub -- \
              --exclude-test=jobs.test.test_jobs_controller_google.TestJobsControllerGoogle \
              --exclude-test=jobs.test.test_jobs_controller_local.TestJobsControllerLocal

      - run:
          command: |
            source venv/bin/activate
            tox -c ./servers/cromwell

      - store_artifacts:
          path: test-reports
          destination: test-reports

