# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

job_defaults: &job_defaults
  machine:
    image: circleci/classic:latest
  working_directory: ~/job-manager

run_env_setup: &run_env_setup
  run:
    name: Setup Environment Variables
    command: |
      echo 'export PATH="${PATH}:${HOME}/job-manager/git-secrets"' >> $BASH_ENV

run_secret_setup: &run_secret_setup
  run:
    name: Install git secrets and configure minnie-kenny.sh
    command: |
      git clone https://github.com/awslabs/git-secrets.git
      pushd git-secrets >/dev/null
      git checkout ad82d68ee924906a0401dfd48de5057731a9bc84
      popd >/dev/null
      ./minnie-kenny.sh -f

jobs:
  ui:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *run_env_setup
      - <<: *run_secret_setup
      - restore_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "ui/package.json" }}
      - run:
          name: nvm install node and UI dependencies
          command: |
            /opt/circleci/.nvm/nvm.sh install --lts
            cd ui
            npm install
            npm install -g @angular/cli@1.7.4
      - save_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "ui/package.json" }}
          paths:
            - "ui/node_modules"
      - run:
          name: Rebuild swagger
          command: |
            /bin/bash ./scripts/rebuild_swagger.sh
      - run:
          name: Lint angular code with ng lint
          command: |
            /opt/circleci/.nvm/nvm.sh install --lts
            cd ui
            ng lint --type-check
      - run:
          name: Run UI unit tests
          command: |
            /opt/circleci/.nvm/nvm.sh install --lts
            cd ui
            ng test --single-run -sm=false --browsers=ChromeHeadless
      - run:
          name: Ensure the UI builds for prod
          # Target production to emulate deployment, but a dev environment
          # because we do not have a prod environment file.
          # https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds
          command: |
            /opt/circleci/.nvm/nvm.sh install --lts
            cd ui
            ng build --target=production --environment=dev

  backends:
    <<: *job_defaults
    environment:
      - KEEP_TEST_DSUB_FILES: true
      - GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/gcloud-service-key.json
    steps:
      - checkout
      - <<: *run_env_setup
      - <<: *run_secret_setup
      - restore_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "servers/dsub/requirements.txt" }}
      - restore_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "servers/cromwell/requirements.txt" }}
      - restore_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "servers/jm_utils/requirements.txt" }}
      - run:
          name: Rebuild swagger
          command: |
            /bin/bash ./scripts/rebuild_swagger.sh
      - run:
          name: Install tox and yapf
          # tox (and detox) fail with older versions of more-itertools: https://github.com/pytest-dev/pytest/issues/4770
          command: |
            pyenv install 3.6.3
            pyenv global 3.6.3
            python --version
            pip install --upgrade pip
            pip install tox>=3.13.2 pytest>=4.6.5 yapf
      - run:
          name: Lint python code with yapf
          command: |
            sh ./scripts/yapf_lint.sh
      - run:
          name: Run dsub server tests
          command: |
            if [[ -z "$GCLOUD_SERVICE_KEY" || "${CIRCLE_BRANCH}" != "master" ]]; then
              tox -p 8 -c ./servers/dsub -- \
                --exclude-test=jobs.test.test_jobs_controller_google.TestJobsControllerGoogle \
                --exclude-test=jobs.test.test_jobs_controller_google_v2.TestJobsControllerGoogleV2
            else
              echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > /home/circleci/gcloud-service-key.json
              tox -p 8 -c ./servers/dsub
              rm /home/circleci/gcloud-service-key.json
            fi
      - run:
          name: Run cromwell server tests
          command: |
            tox -c ./servers/cromwell
      - run:
          name: Run jm_utils server tests
          command: |
            tox -c ./servers/jm_utils
      - save_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "servers/dsub/requirements.txt" }}
          paths:
            - "servers/dsub/.tox"
      - save_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "servers/cromwell/requirements.txt" }}
          paths:
            - "servers/cromwell/.tox"
      - save_cache:
          key: node-modules-{{ .Branch }}--{{ checksum "servers/jm_utils/requirements.txt" }}
          paths:
            - "servers/jm_utils/.tox"

  secrets:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *run_env_setup
      - <<: *run_secret_setup
      - run:
          name: Check for git secrets
          command: |
            git secrets --scan-history

workflows:
  version: 2
  ui_and_backends_and_secrets:
    jobs:
      - ui
      - backends
      - secrets
