# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    environment:
      - NVM_DIR: /opt/circleci/.nvm
    machine:
      image: circleci/classic:latest

    working_directory: ~/job-monitor
    steps:
      # Download the relevant code
      - checkout

      # Setup
      - run:
          name: Install tox and yapf
          command: |
            pip install tox yapf
      - run:
          name: Add nvm to bash environment
          # Adding this line to the BASH_ENV file enables use of nvm in all shells
          command: |
            NVM_ACTIVATE="\n[ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\""
            command printf "${NVM_ACTIVATE}" >> "$BASH_ENV"
      - run:
          name: nvm install node and UI dependencies
          command: |
            nvm install 8.5.0
            cd ui
            npm install
            npm install -g @angular/cli
      # Linting
      - run:
          name: Lint python code with yapf
          command: |
            sh ./scripts/yapf_lint.sh
      - run:
          name: Lint angular code with ng lint
          command: |
            nvm use 8.5.0
            cd ui
            ng lint --type-check

      # Unit and Integration Tests
      # TODO(calbach): Cache the tox venvs per https://discuss.circleci.com/t/cached-venv-in-tox/1499.
      - run:
          # TODO(calbach): Re-enable Google tests, fails due to lack of auth.
          name: Run dsub server tests
          command: |
            tox -c ./servers/dsub -- \
              --exclude-test=jobs.test.test_jobs_controller_google.TestJobsControllerGoogle
      - run:
          name: Run cromwell server tests
          command: |
            tox -c ./servers/cromwell
      - run:
          name: Run UI unit tests
          command: |
            nvm use 8.5.0
            cd ui
            ng test --watch=false

      - store_artifacts:
          path: /tmp
          destination: dsub-local-job-directories
