# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  # TODO(calbach): Add linting tests.
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/job-monitor

    steps:
      - checkout
      - restore_cache:
          key: venv
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install tox yapf
      - save_cache:
          key: venv
          paths:
            - "venv"
      - run:
          name: Run yapf linter
          command: |
            set +e
            python_files_command="git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 --cached --name-only | grep '\.py$' | grep -v 'servers/[^\/]*/jobs/models' | grep -v 'setup.py'"
            python_files=$(eval $python_files_command)
            yapf_out=$(eval yapf -d $python_files || :)
            if [ -z "$yapf_out" ]; then
              echo "Passed yapf linter!"
              exit 0
            else
              echo "Failed yapf linter, please run:"
              echo "yapf -i \$($python_files_command)"
              exit 1
            fi

      # TODO(calbach): Cache the tox venvs per https://discuss.circleci.com/t/cached-venv-in-tox/1499.
      - run:
          # TODO(calbach): Re-enable Google tests, fails due to lack of auth.
          command: |
            source venv/bin/activate
            tox -c ./servers/dsub -- \
              --exclude-test=jobs.test.test_jobs_controller_google.TestJobsControllerGoogle

      - run:
          command: |
            source venv/bin/activate
            tox -c ./servers/cromwell

      - store_artifacts:
          path: test-reports
          destination: test-reports
