# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class EventDetail(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, time=None, content=None):
        """
        EventDetail - a model defined in Swagger

        :param time: The time of this EventDetail.
        :type time: datetime
        :param content: The content of this EventDetail.
        :type content: str
        """
        self.swagger_types = {
            'time': datetime,
            'content': str
        }

        self.attribute_map = {
            'time': 'time',
            'content': 'content'
        }

        self._time = time
        self._content = content

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventDetail of this EventDetail.
        :rtype: EventDetail
        """
        return deserialize_model(dikt, cls)

    @property
    def time(self):
        """
        Gets the time of this EventDetail.

        :return: The time of this EventDetail.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """
        Sets the time of this EventDetail.

        :param time: The time of this EventDetail.
        :type time: datetime
        """

        self._time = time

    @property
    def content(self):
        """
        Gets the content of this EventDetail.

        :return: The content of this EventDetail.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """
        Sets the content of this EventDetail.

        :param content: The content of this EventDetail.
        :type content: str
        """

        self._content = content

