# coding: utf-8

from __future__ import absolute_import
from jobs.models.task_metadata import TaskMetadata
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ExtendedFields(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, user_id=None, status_detail=None, logs=None, envs=None, parent_job_id=None, timing_url=None, tasks=None):
        """
        ExtendedFields - a model defined in Swagger

        :param user_id: The user_id of this ExtendedFields.
        :type user_id: str
        :param status_detail: The status_detail of this ExtendedFields.
        :type status_detail: str
        :param logs: The logs of this ExtendedFields.
        :type logs: object
        :param envs: The envs of this ExtendedFields.
        :type envs: object
        :param parent_job_id: The parent_job_id of this ExtendedFields.
        :type parent_job_id: str
        :param timing_url: The timing_url of this ExtendedFields.
        :type timing_url: str
        :param tasks: The tasks of this ExtendedFields.
        :type tasks: List[TaskMetadata]
        """
        self.swagger_types = {
            'user_id': str,
            'status_detail': str,
            'logs': object,
            'envs': object,
            'parent_job_id': str,
            'timing_url': str,
            'tasks': List[TaskMetadata]
        }

        self.attribute_map = {
            'user_id': 'userId',
            'status_detail': 'statusDetail',
            'logs': 'logs',
            'envs': 'envs',
            'parent_job_id': 'parentJobId',
            'timing_url': 'timingUrl',
            'tasks': 'tasks'
        }

        self._user_id = user_id
        self._status_detail = status_detail
        self._logs = logs
        self._envs = envs
        self._parent_job_id = parent_job_id
        self._timing_url = timing_url
        self._tasks = tasks

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExtendedFields of this ExtendedFields.
        :rtype: ExtendedFields
        """
        return deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """
        Gets the user_id of this ExtendedFields.
        The user associated with the job

        :return: The user_id of this ExtendedFields.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this ExtendedFields.
        The user associated with the job

        :param user_id: The user_id of this ExtendedFields.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def status_detail(self):
        """
        Gets the status_detail of this ExtendedFields.
        Longer text description of the job status.

        :return: The status_detail of this ExtendedFields.
        :rtype: str
        """
        return self._status_detail

    @status_detail.setter
    def status_detail(self, status_detail):
        """
        Sets the status_detail of this ExtendedFields.
        Longer text description of the job status.

        :param status_detail: The status_detail of this ExtendedFields.
        :type status_detail: str
        """

        self._status_detail = status_detail

    @property
    def logs(self):
        """
        Gets the logs of this ExtendedFields.
        Map of type of log file to its file location

        :return: The logs of this ExtendedFields.
        :rtype: object
        """
        return self._logs

    @logs.setter
    def logs(self, logs):
        """
        Sets the logs of this ExtendedFields.
        Map of type of log file to its file location

        :param logs: The logs of this ExtendedFields.
        :type logs: object
        """

        self._logs = logs

    @property
    def envs(self):
        """
        Gets the envs of this ExtendedFields.
        Map of ENV variables associated with the job

        :return: The envs of this ExtendedFields.
        :rtype: object
        """
        return self._envs

    @envs.setter
    def envs(self, envs):
        """
        Sets the envs of this ExtendedFields.
        Map of ENV variables associated with the job

        :param envs: The envs of this ExtendedFields.
        :type envs: object
        """

        self._envs = envs

    @property
    def parent_job_id(self):
        """
        Gets the parent_job_id of this ExtendedFields.
        The parent job ID for the job

        :return: The parent_job_id of this ExtendedFields.
        :rtype: str
        """
        return self._parent_job_id

    @parent_job_id.setter
    def parent_job_id(self, parent_job_id):
        """
        Sets the parent_job_id of this ExtendedFields.
        The parent job ID for the job

        :param parent_job_id: The parent_job_id of this ExtendedFields.
        :type parent_job_id: str
        """

        self._parent_job_id = parent_job_id

    @property
    def timing_url(self):
        """
        Gets the timing_url of this ExtendedFields.
        URL for tasks timing diagram.

        :return: The timing_url of this ExtendedFields.
        :rtype: str
        """
        return self._timing_url

    @timing_url.setter
    def timing_url(self, timing_url):
        """
        Sets the timing_url of this ExtendedFields.
        URL for tasks timing diagram.

        :param timing_url: The timing_url of this ExtendedFields.
        :type timing_url: str
        """

        self._timing_url = timing_url

    @property
    def tasks(self):
        """
        Gets the tasks of this ExtendedFields.

        :return: The tasks of this ExtendedFields.
        :rtype: List[TaskMetadata]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks):
        """
        Sets the tasks of this ExtendedFields.

        :param tasks: The tasks of this ExtendedFields.
        :type tasks: List[TaskMetadata]
        """

        self._tasks = tasks

