# coding: utf-8

from __future__ import absolute_import
from jobs.models.query_jobs_result import QueryJobsResult
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class QueryJobsResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, results=None):
        """
        QueryJobsResponse - a model defined in Swagger

        :param results: The results of this QueryJobsResponse.
        :type results: List[QueryJobsResult]
        """
        self.swagger_types = {
            'results': List[QueryJobsResult]
        }

        self.attribute_map = {
            'results': 'results'
        }

        self._results = results

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryJobsResponse of this QueryJobsResponse.
        :rtype: QueryJobsResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def results(self):
        """
        Gets the results of this QueryJobsResponse.

        :return: The results of this QueryJobsResponse.
        :rtype: List[QueryJobsResult]
        """
        return self._results

    @results.setter
    def results(self, results):
        """
        Sets the results of this QueryJobsResponse.

        :param results: The results of this QueryJobsResponse.
        :type results: List[QueryJobsResult]
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")

        self._results = results

