# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UpdateJobLabelsResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, labels=None):
        """
        UpdateJobLabelsResponse - a model defined in Swagger

        :param labels: The labels of this UpdateJobLabelsResponse.
        :type labels: object
        """
        self.swagger_types = {
            'labels': object
        }

        self.attribute_map = {
            'labels': 'labels'
        }

        self._labels = labels

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateJobLabelsResponse of this UpdateJobLabelsResponse.
        :rtype: UpdateJobLabelsResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def labels(self):
        """
        Gets the labels of this UpdateJobLabelsResponse.
        All job labels, after the update has been applied.

        :return: The labels of this UpdateJobLabelsResponse.
        :rtype: object
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """
        Sets the labels of this UpdateJobLabelsResponse.
        All job labels, after the update has been applied.

        :param labels: The labels of this UpdateJobLabelsResponse.
        :type labels: object
        """

        self._labels = labels

