# Note: This is the dockerfile for development purposes

FROM us.gcr.io/broad-dsp-gcr-public/base/python:3.10-debian

WORKDIR /app

ADD servers/jm_utils /app/jm_utils
ADD servers/cromwell/jobs /app/jobs
COPY servers/cromwell/requirements.txt /app/jobs
COPY servers/cromwell/constraints.txt /app/jobs
# Below is a link explaining where the individual PyYAML install command comes from
# https://github.com/yaml/pyyaml/issues/736#issuecomment-1653209769
# In short, due to Cython 3 being released, PyYAML needs to have it's Cython dependency contrained, otherwise it will fail to install due to deprecated features
# However installation of PyYAML uses a "wheel", which is basically a pre-compiled version of the package
# This is problematic for requirements.txt as it cannot specify a wheel, only a source package
# So we need to install PyYAML separately with the constraint defined in constraints.txt
RUN cd jobs && PIP_CONSTRAINT=constraints.txt pip install PyYAML==5.4.1
RUN cd jobs && pip install -r requirements.txt
# We installed jm_utils so don't need local copy anymore, which breaks imports
RUN rm -rf jm_utils

# Missing required arguments -b PORT, -e ... which must be provided by the
# docker image user.
ENTRYPOINT ["/bin/bash", "/scripts/await_md5_match.sh", "/app/jobs/models/.jobs.yaml.md5", "--", "gunicorn", "jobs:run()"]
