#!/bin/sh

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty
status=0

echo "Running ng lint for typscript files..."
cd ./ui
ng lint >/dev/null
ret_code=$?

if [ $ret_code != 0 ]; then
	echo "Please run ng lint from the ui/ directory and fix your typescript files"
	status=1
else
	echo "Passed ng lint!"
fi

# Close stdin and exit with the correct status
exec <&-
exit $status
