version: '2.1'
services:
  jmui:
    extends:
      file: quickstart-common-compose.yml
      service: jmui
    command: ["npm", "run-script", "ng", "--", "serve", "--host", "jmui"]
    volumes:
      - ${PWD}/ui/assets/environments/environment.cromwell.instance.json:/ui/src/assets/environments/environment.json
  cromwell:
    image: databiosphere/job-manager-api-cromwell:v0.2.0
    extends:
      file: quickstart-common-compose.yml
      service: cromwell
    environment:
      - USE_CAAS=False
  jobs-proxy:
    extends:
      file: quickstart-common-compose.yml
      service: jobs-proxy
    links:
      - jmui
      - cromwell:jmapi
