# coding: utf-8

from __future__ import absolute_import
from jobs.models.aggregation_entry import AggregationEntry
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Aggregation(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, key=None, entries=None):
        """
        Aggregation - a model defined in Swagger

        :param name: The name of this Aggregation.
        :type name: str
        :param key: The key of this Aggregation.
        :type key: str
        :param entries: The entries of this Aggregation.
        :type entries: List[AggregationEntry]
        """
        self.swagger_types = {
            'name': str,
            'key': str,
            'entries': List[AggregationEntry]
        }

        self.attribute_map = {
            'name': 'name',
            'key': 'key',
            'entries': 'entries'
        }

        self._name = name
        self._key = key
        self._entries = entries

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Aggregation of this Aggregation.
        :rtype: Aggregation
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this Aggregation.

        :return: The name of this Aggregation.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Aggregation.

        :param name: The name of this Aggregation.
        :type name: str
        """

        self._name = name

    @property
    def key(self):
        """
        Gets the key of this Aggregation.

        :return: The key of this Aggregation.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this Aggregation.

        :param key: The key of this Aggregation.
        :type key: str
        """

        self._key = key

    @property
    def entries(self):
        """
        Gets the entries of this Aggregation.

        :return: The entries of this Aggregation.
        :rtype: List[AggregationEntry]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """
        Sets the entries of this Aggregation.

        :param entries: The entries of this Aggregation.
        :type entries: List[AggregationEntry]
        """

        self._entries = entries

