# coding: utf-8

from __future__ import absolute_import
from jobs.models.authentication_capability import AuthenticationCapability
from jobs.models.display_field import DisplayField
from jobs.models.time_frame import TimeFrame
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class CapabilitiesResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, authentication=None, display_fields=None, common_labels=None, query_extensions=None, aggregation_time_frames=None):
        """
        CapabilitiesResponse - a model defined in Swagger

        :param authentication: The authentication of this CapabilitiesResponse.
        :type authentication: AuthenticationCapability
        :param display_fields: The display_fields of this CapabilitiesResponse.
        :type display_fields: List[DisplayField]
        :param common_labels: The common_labels of this CapabilitiesResponse.
        :type common_labels: List[str]
        :param query_extensions: The query_extensions of this CapabilitiesResponse.
        :type query_extensions: List[str]
        :param aggregation_time_frames: The aggregation_time_frames of this CapabilitiesResponse.
        :type aggregation_time_frames: List[TimeFrame]
        """
        self.swagger_types = {
            'authentication': AuthenticationCapability,
            'display_fields': List[DisplayField],
            'common_labels': List[str],
            'query_extensions': List[str],
            'aggregation_time_frames': List[TimeFrame]
        }

        self.attribute_map = {
            'authentication': 'authentication',
            'display_fields': 'displayFields',
            'common_labels': 'commonLabels',
            'query_extensions': 'queryExtensions',
            'aggregation_time_frames': 'aggregationTimeFrames'
        }

        self._authentication = authentication
        self._display_fields = display_fields
        self._common_labels = common_labels
        self._query_extensions = query_extensions
        self._aggregation_time_frames = aggregation_time_frames

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CapabilitiesResponse of this CapabilitiesResponse.
        :rtype: CapabilitiesResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def authentication(self):
        """
        Gets the authentication of this CapabilitiesResponse.

        :return: The authentication of this CapabilitiesResponse.
        :rtype: AuthenticationCapability
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication):
        """
        Sets the authentication of this CapabilitiesResponse.

        :param authentication: The authentication of this CapabilitiesResponse.
        :type authentication: AuthenticationCapability
        """

        self._authentication = authentication

    @property
    def display_fields(self):
        """
        Gets the display_fields of this CapabilitiesResponse.
        Fields on QueryJobsResult returned from POST /jobs/query populated on some or all jobs. The fields are mapped to their display names, in order of importance. Extended fields and labels can be included, such as 'label.foo' or 'extensions.userId' 

        :return: The display_fields of this CapabilitiesResponse.
        :rtype: List[DisplayField]
        """
        return self._display_fields

    @display_fields.setter
    def display_fields(self, display_fields):
        """
        Sets the display_fields of this CapabilitiesResponse.
        Fields on QueryJobsResult returned from POST /jobs/query populated on some or all jobs. The fields are mapped to their display names, in order of importance. Extended fields and labels can be included, such as 'label.foo' or 'extensions.userId' 

        :param display_fields: The display_fields of this CapabilitiesResponse.
        :type display_fields: List[DisplayField]
        """

        self._display_fields = display_fields

    @property
    def common_labels(self):
        """
        Gets the common_labels of this CapabilitiesResponse.
        Common labels which are present on most jobs returned

        :return: The common_labels of this CapabilitiesResponse.
        :rtype: List[str]
        """
        return self._common_labels

    @common_labels.setter
    def common_labels(self, common_labels):
        """
        Sets the common_labels of this CapabilitiesResponse.
        Common labels which are present on most jobs returned

        :param common_labels: The common_labels of this CapabilitiesResponse.
        :type common_labels: List[str]
        """

        self._common_labels = common_labels

    @property
    def query_extensions(self):
        """
        Gets the query_extensions of this CapabilitiesResponse.
        Fields on ExtendedQueryFields which are queryable

        :return: The query_extensions of this CapabilitiesResponse.
        :rtype: List[str]
        """
        return self._query_extensions

    @query_extensions.setter
    def query_extensions(self, query_extensions):
        """
        Sets the query_extensions of this CapabilitiesResponse.
        Fields on ExtendedQueryFields which are queryable

        :param query_extensions: The query_extensions of this CapabilitiesResponse.
        :type query_extensions: List[str]
        """

        self._query_extensions = query_extensions

    @property
    def aggregation_time_frames(self):
        """
        Gets the aggregation_time_frames of this CapabilitiesResponse.
        Time frames supported by the /aggregations endpoint.

        :return: The aggregation_time_frames of this CapabilitiesResponse.
        :rtype: List[TimeFrame]
        """
        return self._aggregation_time_frames

    @aggregation_time_frames.setter
    def aggregation_time_frames(self, aggregation_time_frames):
        """
        Sets the aggregation_time_frames of this CapabilitiesResponse.
        Time frames supported by the /aggregations endpoint.

        :param aggregation_time_frames: The aggregation_time_frames of this CapabilitiesResponse.
        :type aggregation_time_frames: List[TimeFrame]
        """

        self._aggregation_time_frames = aggregation_time_frames

