# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DisplayField(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, field=None, display=None):
        """
        DisplayField - a model defined in Swagger

        :param field: The field of this DisplayField.
        :type field: str
        :param display: The display of this DisplayField.
        :type display: str
        """
        self.swagger_types = {
            'field': str,
            'display': str
        }

        self.attribute_map = {
            'field': 'field',
            'display': 'display'
        }

        self._field = field
        self._display = display

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DisplayField of this DisplayField.
        :rtype: DisplayField
        """
        return deserialize_model(dikt, cls)

    @property
    def field(self):
        """
        Gets the field of this DisplayField.

        :return: The field of this DisplayField.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """
        Sets the field of this DisplayField.

        :param field: The field of this DisplayField.
        :type field: str
        """

        self._field = field

    @property
    def display(self):
        """
        Gets the display of this DisplayField.

        :return: The display of this DisplayField.
        :rtype: str
        """
        return self._display

    @display.setter
    def display(self, display):
        """
        Sets the display of this DisplayField.

        :param display: The display of this DisplayField.
        :type display: str
        """

        self._display = display

