# coding: utf-8

from __future__ import absolute_import
from jobs.models.status_count import StatusCount
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class StatusCounts(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, counts=None):
        """
        StatusCounts - a model defined in Swagger

        :param counts: The counts of this StatusCounts.
        :type counts: List[StatusCount]
        """
        self.swagger_types = {
            'counts': List[StatusCount]
        }

        self.attribute_map = {
            'counts': 'counts'
        }

        self._counts = counts

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StatusCounts of this StatusCounts.
        :rtype: StatusCounts
        """
        return deserialize_model(dikt, cls)

    @property
    def counts(self):
        """
        Gets the counts of this StatusCounts.

        :return: The counts of this StatusCounts.
        :rtype: List[StatusCount]
        """
        return self._counts

    @counts.setter
    def counts(self, counts):
        """
        Sets the counts of this StatusCounts.

        :param counts: The counts of this StatusCounts.
        :type counts: List[StatusCount]
        """

        self._counts = counts

