# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UpdateJobLabelsRequest(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, labels=None):
        """
        UpdateJobLabelsRequest - a model defined in Swagger

        :param labels: The labels of this UpdateJobLabelsRequest.
        :type labels: object
        """
        self.swagger_types = {
            'labels': object
        }

        self.attribute_map = {
            'labels': 'labels'
        }

        self._labels = labels

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateJobLabelsRequest of this UpdateJobLabelsRequest.
        :rtype: UpdateJobLabelsRequest
        """
        return deserialize_model(dikt, cls)

    @property
    def labels(self):
        """
        Gets the labels of this UpdateJobLabelsRequest.
        Labels to be merged into the existing job labels. Overwrites the label values for all given keys. Existing labels on the job which are not referenced in this request are left unmodified. 

        :return: The labels of this UpdateJobLabelsRequest.
        :rtype: object
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """
        Sets the labels of this UpdateJobLabelsRequest.
        Labels to be merged into the existing job labels. Overwrites the label values for all given keys. Existing labels on the job which are not referenced in this request are left unmodified. 

        :param labels: The labels of this UpdateJobLabelsRequest.
        :type labels: object
        """

        self._labels = labels

