# Note: This is the dockerfile for development purposes

FROM node:18

# Install python 3, needed for npm packages
RUN apt-get update && apt-get -y install python3

WORKDIR /ui
ADD .yarnrc.yml package.json yarn.lock angular.json /ui/
ADD .yarn/releases/* /ui/.yarn/releases/
RUN yarn install
ENTRYPOINT [ "/scripts/await_md5_match.sh", "/ui/src/app/shared/model/.jobs.yaml.md5", "--" ]
