swagger: '2.0'
info:
  title: Job Monitor Service
  description: Job Monitor API for interacting with asynchronous batch jobs and workflows.
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  version: ''
produces:
  - application/json
paths:
  '/api/workflows/{version}/{id}/abort':
    post:
      summary: Abort a workflow based on workflow id
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: id
          description: Workflow ID
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
          schema:
            $ref: '#/definitions/WorkflowAbortResponse'
        '400':
          description: Malformed Workflow ID
        '403':
          description: Workflow in terminal status
        '404':
          description: Workflow ID Not Found
        '500':
          description: Internal Error
  '/api/workflows/{version}/query':
    post:
      summary: Query workflows by start dates, end dates, names, ids, or statuses.
      parameters:
        - name: version
          description: API version
          required: true
          type: string
          in: path
          default: v1
        - name: parameters
          required: true
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/WorkflowQueryParameter'
          description: >
            Same query parameters as GET /query endpoint, submitted as a json list.
            Example: [{"status":"Success"},{"status":"Failed"}]
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
          schema:
            $ref: '#/definitions/WorkflowQueryResponse'
        '400':
          description: Malformed Request
        '500':
          description: Internal Error
  '/api/workflows/{version}/{id}/metadata':
    get:
      summary: Query for workflow and call-level metadata for a specified workflow
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v2
        - name: id
          description: Workflow ID
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
          schema:
            $ref: '#/definitions/WorkflowMetadataResponse'
        '400':
          description: Malformed Workflow ID
        '404':
          description: Workflow ID Not Found
        '500':
          description: Internal Error
definitions:
  WorkflowAbortResponse:
    required:
      - id
      - status
    properties:
      id:
        type: string
        description: The identifier of the workflow
      status:
        type: string
        description: The status of the workflow
  WorkflowMetadataResponse:
    description: Workflow and call level metadata
    required:
      - id
      - status
      - submission
    properties:
      id:
        type: string
        description: The identifier of the workflow
      status:
        type: string
        description: The status of the workflow
      submission:
        type: string
        format: date-time
        description: Submission datetime of the workflow in ISO8601 format with milliseconds
      start:
        type: string
        format: date-time
        description: Start datetime of the workflow in ISO8601 format with milliseconds
      end:
        type: string
        format: date-time
        description: End datetime of the workflow in ISO8601 format with milliseconds
      inputs:
        type: object
        description: Map of input keys to input values
      outputs:
        type: object
        description: Map of output keys to output values
      labels:
        type: object
        description: Custom workflow labels with string values
      calls:
        $ref: '#/definitions/CallMetadata'
      failures:
        type: array
        items:
          $ref: '#/definitions/FailureMessage'
  CallMetadata:
    description: Call level metadata
    required:
      - inputs
      - executionStatus
    properties:
      inputs:
        type: object
        description: Mapping of input fully qualified names to stringified values
      executionStatus:
        type: string
        description: Status in Cromwell execution terms.
      start:
        type: string
        format: date-time
        description: Start datetime of the call execution in ISO8601 format with milliseconds
      end:
        type: string
        format: date-time
        description: End datetime of the call execution in ISO8601 format with milliseconds
      jobId:
        type: string
        description: Backend-specific job ID
      failures:
        type: array
        items:
          $ref: '#/definitions/FailureMessage'
      returnCode:
        type: integer
        description: Call execution return code
      stdout:
        type: string
        description: Path to the standard output file for this call
      stderr:
        type: string
        description: Path to the standard error file for this call
  FailureMessage:
    description: Failure messages
    required:
      - failure
      - timestamp
    properties:
      failure:
        type: string
        description: The failure message
      timestamp:
        type: string
        format: date-time
        description: The time at which this failure occurred
  WorkflowQueryParameter:
    description: Workflow query parameters
    minProperties: 1
    maxProperties: 1
    properties:
      start:
        type: string
        format: date-time
        description: >
          Returns only workflows with an equal or later start datetime.  Can be specified at most once.
          If both start and end date are specified, start date must be before or equal to end date.
      end:
        type: string
        format: date-time
        description: >
          Returns only workflows with an equal or earlier end datetime.  Can be specified at most once.
          If both start and end date are specified, start date must be before or equal to end date.
      status:
        type: string
        enum:
          - Submitted
          - Running
          - Aborting
          - Failed
          - Succeeded
          - Aborted
        description: >
          Returns only workflows with the specified status.  If specified multiple times,
          returns workflows in any of the specified statuses.
      name:
        type: string
        pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
        description: >
          Returns only workflows with the specified name.  If specified multiple times,
          returns workflows with any of the specified names.
      parentId:
        type: string
        format: string
        description: >
          Returns only workflows with the given parent ID. This parameter may be
          unsupported for some backends or required for others.
  WorkflowQueryResponse:
    description: Response to a workflow query
    required:
      - results
    properties:
      results:
        type: array
        items:
          $ref: '#/definitions/WorkflowQueryResult'
  WorkflowQueryResult:
    description: Result for an individual workflow returned by a workflow query
    required:
      - id
      - name
      - status
      - start
    properties:
      id:
        type: string
        description: Workflow ID
      name:
        type: string
        description: Workflow name
      status:
        type: string
        description: Workflow status
      start:
        type: string
        format: date-time
        description: Workflow start datetime
      end:
        type: string
        format: date-time
        description: Workflow end datetime
      labels:
        type: object
        description: Custom workflow labels with string values
